config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', HomeView.as_view(), name='home'),
    path('', include('products.urls', namespace='products')),
    path('', include('orders.urls', namespace='orders')),
    path('panel/', include('panel.urls', namespace='panel')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

panel/urls.py
from django.urls import path
from . import views


app_name = 'panel'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('orders/', views.OrderListView.as_view(), name='order_list'),
    path('orders/<int:pk>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('payments/', views.PaymentListView.as_view(), name='payments'),
]

products/urls.py
from django.urls import path
from . import views


app_name = 'products'

urlpatterns = [
    path('products/', views.ProductList.as_view(), name='products_list'),
    path('products/<slug:slug>/', views.ProductDetail.as_view(), name='products_detail'),
    path('category/<slug:slug>/', views.CategoryProductList.as_view(), name='category_products'),
]

panel/models.py
from django.db import models

# Create your models here.

panel/views.py
from django.shortcuts import render
from django.views import View
from django.views.generic import UpdateView, ListView, DetailView
from accounts.models import User
from orders.models import Order, Payment
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin


class HomeView(View):
    def get(self, request):
        return render(request, 'panel/home.html')


class ProfileView(SuccessMessageMixin, UpdateView):
    fields = ('first_name', 'last_name', 'email', 'image')
    template_name = 'panel/users/profile.html'
    success_url = reverse_lazy('panel:profile')
    success_message = 'اطلاعات پروفایل با موفقیت ویرایش شد.'

    def get_object(self):
        return self.request.user


class OrderListView(ListView):
    template_name = 'panel/users/order_list.html'

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)


class OrderDetailView(DetailView):
    template_name = 'panel/users/order_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        total_price = self.get_object().get_total_cost(without_discount=True)
        total_cost = self.get_object().get_total_cost(without_discount=False)
        context["total_price"] = total_price
        context["total_cost"] = total_cost
        context["total_discount"] = total_price - total_cost
        return context

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)


class PaymentListView(ListView):
    template_name = 'panel/users/payment_list.html'

    def get_queryset(self):
        return Payment.objects.filter(user=self.request.user)

templates/panel/users/order_detail.html
{% extends 'panel/base.html' %}
{% load humanize %}
{% load panel_base_tags %}

{% block panel_title %} جزئیات سفارش شماره {{order.id}} {% endblock %}
{% block panel_content %}
<div class="row">
    <div class="col-md-6">
        <strong>وضعیت سفارش:</strong>
        {% if order.paid %}
            <span class="badge badge-success">پرداخت شده</span>
        {% else %}
            <span class="badge badge-danger">پرداخت نشده</span>
        {% endif %}
    </div>
    <div class="col-md-6">
        <strong>تاریخ سفارش:</strong> {% jalali_date order.created %}
    </div>
    <div class="col-md-6">
        <strong>نام گیرنده:</strong> {{order.recipient_name}}
    </div>
    <div class="col-md-6">
        <strong>شماره تماس گیرنده:</strong> {{order.recipient_phone_number}}
    </div>
    <div class="col-md-12">
        <strong>آدرس گیرنده:</strong> {{order.recipient_address}}
    </div>
    <br><br>
    <div class="col-md-4">
        <strong>مبلغ کل:</strong> {{total_price|intcomma:False}} تومان
    </div>
    <div class="col-md-4">
        <strong>مبلغ پرداختی:</strong> {{total_cost|intcomma:False}} تومان
    </div>
    <div class="col-md-4">
        <strong>مقدار تخفیف:</strong> {{total_discount|intcomma:False}} تومان
    </div>
    <div class="col-md-12">
        <div class="table-responsive">
            <table class="table m-t-b-50">
                <thead>
                    <tr class="bg-dark text-white text-center">
                        <th>#</th>
                        <th>تصویر محصول</th>
                        <th>نام محصول</th>
                        <th>قیمت واحد</th>
                        <th>تعداد</th>
                        <th>قیمت کل</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in order.items.all %}
                    <tr class="text-center">
                        <td>{{forloop.counter}}</td>
                        <td>
                            <a href="{% url 'products:products_detail' item.product.slug %}" target="_blank">
                                <img src="{{item.product.image.url}}" width="100px">
                            </a>
                        </td>
                        <td>{{item.product.name}}</td>
                        <td>{{item.price|intcomma:False}} تومان</td>
                        <td>{{item.quantity}}</td>
                        <td>{{item.get_item_cost|intcomma:False}} تومان</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

templates/panel/users/order_list.html
{% extends 'panel/base.html' %}
{% load humanize %}
{% load panel_base_tags %}

{% block panel_title %} مشاهده سفارشات{% endblock %}
{% block panel_content %}

<div class="card">
    <div class="card-body">
        <table id="example1" class="table table-striped table-bordered" width="100%">
            <thead>
                <tr class="text-center">
                    <th>ردیف</th>
                    <th>نام گیرنده</th>
                    <th>مبلغ سفارش</th>
                    <th>تاریخ و ساعت</th>
                    <th>وضعیت</th>
                    <th>عملیات</th>
                </tr>
            </thead>
            <tbody>
                {% for order in object_list %}
                    <tr class="text-center">
                        <td>{{ forloop.counter }}</td>
                        <td>{{ order.recipient_name }}</td>
                        <td>{{ order.get_total_cost|intcomma:False }} تومان</td>
                        <td>{% jalali_date order.created %}</td>
                        <td>
                            {% if order.paid %}
                            <span class="badge badge-success">پرداخت شده</span>
                            {% else %}
                            <span class="badge badge-danger">پرداخت نشده</span>
                            {% endif %}
                        </td>
                        <td><a href="{% url 'panel:order_detail' order.id %}" class="btn btn-secondary btn-sm">مشاهده جزئیات</a></td>
                    </tr>
                {% endfor %}
            </tbody>
            <tfoot>
                <tr class="text-center">
                    <th>ردیف</th>
                    <th>نام گیرنده</th>
                    <th>مبلغ سفارش</th>
                    <th>تاریخ و ساعت</th>
                    <th>وضعیت</th>
                    <th>عملیات</th>
                </tr>
            </tfoot>
        </table>
    </div>
</div>

{% endblock %}

templates/panel/users/payment_list.html
{% extends 'panel/base.html' %}
{% load humanize %}
{% load panel_base_tags %}

{% block panel_title %} مشاهده پرداختی‌ها{% endblock %}
{% block panel_content %}

<div class="card">
    <div class="card-body">
        <table id="example1" class="table table-striped table-bordered" width="100%">
            <thead>
                <tr class="text-center">
                    <th>ردیف</th>
                    <th>مبلغ پرداختی</th>
                    <th>تاریخ و ساعت</th>
                    <th>کد رهگیری</th>
                    <th>وضعیت</th>
                    <th>سفارش مربوطه</th>
                </tr>
            </thead>
            <tbody>
                {% for payment in object_list %}
                    <tr class="text-center">
                        <td>{{ forloop.counter }}</td>
                        <td>{{ payment.amount|intcomma:False }} تومان</td>
                        <td>{% jalali_date payment.created %}</td>
                        <td>
                            {% if payment.tracking_code %}
                            {{ payment.tracking_code }}
                            {% else %}
                            ندارد
                            {% endif %}
                        </td>
                        <td>
                            {% if payment.status %}
                            <span class="badge badge-success">موفق</span>
                            {% else %}
                            <span class="badge badge-danger">ناموفق</span>
                            {% endif %}
                        </td>
                        <td><a href="{% url 'panel:order_detail' payment.order.id %}" class="btn btn-secondary btn-sm">مشاهده جزئیات سفارش</a></td>
                    </tr>
                {% endfor %}
            </tbody>
            <tfoot>
                <tr class="text-center">
                    <th>ردیف</th>
                    <th>مبلغ پرداختی</th>
                    <th>تاریخ و ساعت</th>
                    <th>کد رهگیری</th>
                    <th>وضعیت</th>
                    <th>سفارش مربوطه</th>
                </tr>
            </tfoot>
        </table>
    </div>
</div>

{% endblock %}

templates/panel/users/profile.html
{% extends 'panel/base.html' %}
{% load widget_tweaks %}

{% block panel_title %} ویرایش پروفایل {% endblock %}
{% block panel_content %}

{% include 'panel/inc/messages.html' %}

<div class="col-6">
    <form action="" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label>نام</label>
            {% render_field form.first_name class="form-control" placeholder="نام" %}
        </div>
        <div class="form-group">
            <label>نام خانوادگی</label>
            {% render_field form.last_name class="form-control" placeholder="نام خانوادگی" %}
        </div>
        <div class="form-group">
            <label>ایمیل</label>
            {% render_field form.email class="form-control" placeholder="ایمیل" %}
        </div>
        <div class="form-group">
            <label>تصویر پروفایل</label>
            {% render_field form.image class="form-control" placeholder="تصویر پروفایل" %}
        </div>
        <br>
        <input type="submit" value="ویرایش اطلاعات" class="btn btn-primary">
    </form>
</div>

{% endblock %}