config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', HomeView.as_view(), name='home'),
    path('', include('products.urls', namespace='products')),
    path('', include('orders.urls', namespace='orders')),
    path('panel/', include('panel.urls', namespace='panel')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
    path('cart/update/', views.CartUpdateView.as_view(), name='cart_update'),
    path('cart/coupon/', views.CouponCodeView.as_view(), name='cart_coupon'),
    path('cart/coupon/delete/', views.CouponCodeDeleteView.as_view(), name='cart_coupon_delete'),
    path('cart/checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('orders/pay/verify/', views.OrderPayVerify.as_view(), name='pay_verify'),
]

panel/urls.py
from django.urls import path
from . import views


app_name = 'panel'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('orders/', views.OrderListView.as_view(), name='order_list'),
    path('orders/<int:pk>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('payments/', views.PaymentListView.as_view(), name='payments'),
]

products/urls.py
from django.urls import path
from . import views


app_name = 'products'

urlpatterns = [
    path('products/', views.ProductList.as_view(), name='products_list'),
    path('products/<slug:slug>/', views.ProductDetail.as_view(), name='products_detail'),
    path('category/<slug:slug>/', views.CategoryProductList.as_view(), name='category_products'),
]

products/models.py
from django.db import models
from .managers import CategoryManager, ProductManager


class Category(models.Model):
    name = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique=True)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = CategoryManager()

    class Meta:
        ordering = ('-id',)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ManyToManyField(Category, related_name='products')
    name = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique=True)
    image = models.ImageField(upload_to='products/images/')
    description = models.TextField()
    price = models.PositiveIntegerField()
    stock_quantity = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = ProductManager()

    class Meta:
        ordering = ('-id',)

    def __str__(self):
        return self.name

    def seprated_price(self):
        return f'{self.price:,}'

    def categories(self):
        return ', '.join([category.name for category in self.category.all()])
    categories.short_description = 'دسته‌بندی‌ها'

products/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.db.models import Q
from .models import Category, Product
from django.views.generic import ListView, DetailView
from orders.forms import CartAddFormForm
from orders.cart import Cart


class ProductList(ListView):
    paginate_by = 9

    def get_queryset(self):
        orderby = self.request.GET.get('orderby', None)
        search = self.request.GET.get('q', None)

        if search:
            return Product.objects.availables().filter(Q(name__contains=search) | Q(description__contains=search))

        if orderby == 'id_asc':
            return Product.objects.availables().order_by('id')
        elif orderby == 'id_desc':
            return Product.objects.availables().order_by('-id')
        elif orderby == 'price_asc':
            return Product.objects.availables().order_by('price')
        elif orderby == 'price_desc':
            return Product.objects.availables().order_by('-price')
        else:
            return Product.objects.availables()
        return super().get_queryset()


class ProductDetail(DetailView):
    queryset = Product.objects.availables()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = CartAddFormForm
        cart = Cart(self.request)
        context["cart_quantity"] = cart.get_quantity(self.get_object())
        return context


class CategoryProductList(ListView):
    paginate_by = 9
    template_name = 'products/category_product_list.html'

    def get_queryset(self):
        global category
        slug = self.kwargs.get('slug')
        category = get_object_or_404(Category, slug=slug)
        return category.products.availables()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["category"] = category
        return context

templates/products/category_product_list.html
{% extends 'base.html' %}
{% load custom_tags %}

{% block page_title %}لیست محصولات دسته بندی {{category.name}}{% endblock %}
{% block site_title %}لیست محصولات دسته بندی {{category.name}}{% endblock %}

{% block extra_js %}
<script>
    document.getElementById('product-filter').onchange = function() {
        window.location = "?orderby=" + this.value;
    };
    var url = new URL(window.location.href);
    var orderby = url.searchParams.get("orderby");
    if (orderby == 'id_desc') {
        document.getElementsByTagName('option')[0].selected = 'selected'
    } else if (orderby == 'id_asc') {
        document.getElementsByTagName('option')[1].selected = 'selected'
    } else if (orderby == 'price_asc') {
        document.getElementsByTagName('option')[2].selected = 'selected'
    } else if (orderby == 'price_desc') {
        document.getElementsByTagName('option')[3].selected = 'selected'
    }
    
</script>
{% endblock %}

{% block page_content %}
<section class="product-area ptb-100">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12">
                <div class="woocommerce-topbar">
                    <div class="row h-100 justify-content-center align-items-center">
                        <div class="col-lg-9 col-md-7">
                            <div class="woocommerce-result-count">
                                {% comment %} <p>نمایش 1-9 از 11 نتیجه</p> {% endcomment %}
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-5">
                            <div class="woocommerce-topbar-ordering">
                                <div class="select-box">
                                    <select id="product-filter" class="form-control">
                                        <option value="id_desc">بر اساس جدیدترین</option>
                                        <option value="id_asc">بر اساس قدیمی ترین</option>
                                        <option value="price_asc">بر اساس قیمت از کم به زیاد</option>
                                        <option value="price_desc">بر اساس قیمت از زیاد به کم</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            {% for product in object_list %}
                {% product_card product %}
            {% endfor %}

            {% if is_paginated %}
            <div class="col-lg-12 col-md-12">
                <div class="pagination-area">
                    <nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-center" style="direction: ltr;">
                        {% if page_obj.has_previous %}
                            <li class="page-item"><a class="page-link" href="{% url 'products:category_products' category.slug %}?page=1"><i class="icofont-double-right"></i></a></li>
                            <li class="page-item"><a class="page-link" href="{% url 'products:category_products' category.slug %}?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>
                        {% endif %}
                        <li class="page-item active"><span class="page-link">{{ page_obj.number }}</span></li>
                        {% if page_obj.has_next %}
                            <li class="page-item"><a class="page-link" href="{% url 'products:category_products' category.slug %}?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
                            <li class="page-item"><a class="page-link" href="{% url 'products:category_products' category.slug %}?page={{ page_obj.paginator.num_pages }}"><i class="icofont-double-left"></i></a></li>
                        {% endif %}
                        </ul>
                    </nav>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</section>
{% endblock %}

templates/products/product_detail.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block page_title %} {{ product.name }} {% endblock %}
{% block site_title %} {{ product.name }} {% endblock %}

{% block extra_js %}
<script>
    document.getElementById("stock_quantity").setAttribute("max", {{product.stock_quantity}});
</script>
{% endblock %}

{% block page_content %}
<section class="shop-details-area ptb-100">
    <div class="container">
        <div class="shop-details">
            <div class="row h-100 justify-content-center align-items-center">
                <div class="col-lg-4 col-md-12">
                    <div class="product-img-slides">
                        <div class="product-img">
                            <a href="#"><img src="{{ product.image.url }}" alt="product-img"></a>
                        </div>
                        <div class="product-img">
                            <a href="#"><img src="{{ product.image.url }}" alt="product-img"></a>
                        </div>
                    </div>
                </div>

                <div class="col-lg-8 col-md-12">
                    <div class="product-entry-summary">
                        <h3>{{ product.name }}</h3>
                        <h4 class="text-danger">{{ product.seprated_price }} تومان</h4>
                        {{ product.description|truncatewords:30 }}
                        <br><br>
                        <ul class="product-categories">
                            <li>دسته بندی ها:</li>
                            {% for cat in product.category.all %}
                                <li><a href="{% url 'products:category_products' cat.slug %}">{{cat.name}}</a> , </li>
                            {% endfor %}
                        </ul>

                        <ul class="product-categories">
                            <li>موجودی انبار:</li>
                            <li class="text-muted">{{ product.stock_quantity }}</li>
                        </ul>

                        <form action="{% url 'orders:cart_add' product.id %}" method="post">
                            {% csrf_token %}
                            {% render_field form.quantity class="form-control text-center" id="stock_quantity" placeholder="تعداد" value=cart_quantity  %}
                            <input class="btn btn-primary" type="submit" value="افزودن به سبد خرید">
                        </form>

                        <ul class="share-social">
                            <li>اشتراک:</li>
                            <li><a href="#"><i class="icofont-facebook"></i></a></li>
                            <li><a href="#"><i class="icofont-twitter"></i></a></li>
                            <li><a href="#"><i class="icofont-linkedin"></i></a></li>
                            <li><a href="#"><i class="icofont-instagram"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <div class="shop-details-tabs">
                        <ul id="tabs">
                            <li class="active" id="tab_1">توضیحات</li>
                            <li class="inactive" id="tab_2">نظرات</li>
                        </ul>
                        <div class="content show" id="tab_1_content">
                            <div class="shop-description">
                                <h3>توضیحات</h3>
                                {{ product.description|linebreaks }}
                            </div>
                        </div>

                        <div class="content" id="tab_2_content">
                            <div class="shop-reviews">
                                <h3>نظرات</h3>
                                <p>بهترین قالب آژانسی</p>
                                <b>اولین باشید در “انتخاب برتر”</b>
                                <p>رتبه شما</p>

                                <ul>
                                    <li>
                                        <a href="#">
                                            <i class="icofont-star"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="icofont-star"></i>
                                            <i class="icofont-star"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="icofont-star"></i>
                                            <i class="icofont-star"></i>
                                            <i class="icofont-star"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="icofont-star"></i>
                                            <i class="icofont-star"></i>
                                            <i class="icofont-star"></i>
                                            <i class="icofont-star"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="icofont-star"></i>
                                            <i class="icofont-star"></i>
                                            <i class="icofont-star"></i>
                                            <i class="icofont-star"></i>
                                            <i class="icofont-star"></i>
                                        </a>
                                    </li>
                                </ul>

                                <form class="review-form">
                                    <div class="row">
                                        <div class="col-lg-12">
                                           <div class="form-group">
                                                <textarea name="review-message" id="message" cols="30" rows="4" placeholder="نظر شما.." class="form-control"></textarea>
                                           </div>
                                        </div>

                                        <div class="col-lg-6 col-md-6">
                                            <div class="form-group">
                                                <input type="text" placeholder="نام" class="form-control">
                                            </div>
                                        </div>
                                        
                                        <div class="col-lg-6 col-md-6">
                                            <div class="form-group">
                                                <input type="email" placeholder="ایمیل" class="form-control">
                                            </div>
                                        </div>

                                        <div class="col-lg-12 col-md-12">
                                            <button type="submit" class="btn btn-primary">ارسال</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/products/product_list.html
{% extends 'base.html' %}
{% load custom_tags %}

{% block page_title %}
    {% if request.GET.q %}
    نتایج جستجوی برای : {{request.GET.q}}
    {% else %}
    لیست محصولات
    {% endif %}
{% endblock %}

{% block site_title %}
    {% if request.GET.q %}
    نتایج جستجوی برای : {{request.GET.q}}
    {% else %}
    لیست محصولات
    {% endif %}
{% endblock %}

{% block extra_js %}
<script>
    document.getElementById('product-filter').onchange = function() {
        window.location = "?orderby=" + this.value;
    };
    var url = new URL(window.location.href);
    var orderby = url.searchParams.get("orderby");
    if (orderby == 'id_desc') {
        document.getElementsByTagName('option')[0].selected = 'selected'
    } else if (orderby == 'id_asc') {
        document.getElementsByTagName('option')[1].selected = 'selected'
    } else if (orderby == 'price_asc') {
        document.getElementsByTagName('option')[2].selected = 'selected'
    } else if (orderby == 'price_desc') {
        document.getElementsByTagName('option')[3].selected = 'selected'
    }
    
</script>
{% endblock %}

{% block page_content %}
<section class="product-area ptb-100">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12">
                <div class="woocommerce-topbar">
                    <div class="row h-100 justify-content-center align-items-center">
                        <div class="col-lg-9 col-md-7">
                            <div class="woocommerce-result-count">
                                {% comment %} <p>نمایش 1-9 از 11 نتیجه</p> {% endcomment %}
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-5">
                            <div class="woocommerce-topbar-ordering">
                                <div class="select-box">
                                    <select id="product-filter" class="form-control">
                                        <option value="id_desc">بر اساس جدیدترین</option>
                                        <option value="id_asc">بر اساس قدیمی ترین</option>
                                        <option value="price_asc">بر اساس قیمت از کم به زیاد</option>
                                        <option value="price_desc">بر اساس قیمت از زیاد به کم</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            {% for product in object_list %}
                {% product_card product %}
            {% endfor %}

            {% if is_paginated %}
            <div class="col-lg-12 col-md-12">
                <div class="pagination-area">
                    <nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-center" style="direction: ltr;">
                        {% if page_obj.has_previous %}
                            <li class="page-item"><a class="page-link" href="{% url 'products:products_list' %}?page=1"><i class="icofont-double-right"></i></a></li>
                            <li class="page-item"><a class="page-link" href="{% url 'products:products_list' %}?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>
                        {% endif %}
                        <li class="page-item active"><span class="page-link">{{ page_obj.number }}</span></li>
                        {% if page_obj.has_next %}
                            <li class="page-item"><a class="page-link" href="{% url 'products:products_list' %}?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
                            <li class="page-item"><a class="page-link" href="{% url 'products:products_list' %}?page={{ page_obj.paginator.num_pages }}"><i class="icofont-double-left"></i></a></li>
                        {% endif %}
                        </ul>
                    </nav>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</section>
{% endblock %}