config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', HomeView.as_view(), name='home'),
    path('', include('products.urls', namespace='products')),
    path('', include('orders.urls', namespace='orders')),
    path('panel/', include('panel.urls', namespace='panel')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
    path('cart/update/', views.CartUpdateView.as_view(), name='cart_update'),
    path('cart/coupon/', views.CouponCodeView.as_view(), name='cart_coupon'),
    path('cart/coupon/delete/', views.CouponCodeDeleteView.as_view(), name='cart_coupon_delete'),
    path('cart/checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('orders/pay/verify/', views.OrderPayVerify.as_view(), name='pay_verify'),
]

panel/urls.py
from django.urls import path
from . import views


app_name = 'panel'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('orders/', views.OrderListView.as_view(), name='order_list'),
    path('orders/<int:pk>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('payments/', views.PaymentListView.as_view(), name='payments'),
]

products/urls.py
from django.urls import path
from . import views


app_name = 'products'

urlpatterns = [
    path('products/', views.ProductList.as_view(), name='products_list'),
    path('products/<slug:slug>/', views.ProductDetail.as_view(), name='products_detail'),
    path('category/<slug:slug>/', views.CategoryProductList.as_view(), name='category_products'),
]

orders/models.py
from django.db import models
from accounts.models import User
from products.models import Product


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='orders')
    recipient_name = models.CharField(max_length=100)
    recipient_phone_number = models.CharField(max_length=11)
    recipient_address = models.CharField(max_length=250)
    coupon_code = models.CharField(max_length=20, default=None, null=True, blank=True)
    coupon_discount = models.PositiveSmallIntegerField(default=None, null=True, blank=True)
    paid = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, )

    class Meta:
        ordering = ('paid', '-id',)

    def __str__(self):
        return f'order - {self.user}'

    def get_total_cost(self, without_discount=False):
        total = sum(item.get_item_cost() for item in self.items.all())
        total_with_discount = total

        if self.coupon_code and self.coupon_discount:
            discount_price = (self.coupon_discount / 100) * total
            total_with_discount = int(total - discount_price)

        if without_discount:
            return total
        return total_with_discount


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField(default=1, )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('id',)

    def __str__(self):
        return f'orderitem {self.order}'

    def get_item_cost(self):
        return self.price * self.quantity


class Payment(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='user')
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True, blank=True, related_name='order')
    amount = models.PositiveIntegerField()
    authority = models.CharField(max_length=250)
    status = models.BooleanField(default=False)
    tracking_code = models.CharField(max_length=100, default=None, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('status', '-id')

    def __str__(self):
        return f'{self.tracking_code} - {self.status}'


class Coupon(models.Model):
    code = models.CharField(max_length=20, unique=True)
    discount = models.PositiveSmallIntegerField()
    valid_to = models.DateTimeField()
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('id',)

    def __str__(self):
        return f'{self.code} - {self.discount}'

orders/forms.py
from django import forms
from django.core.validators import ValidationError
from orders.models import Order


class CartAddFormForm(forms.Form):
    quantity = forms.IntegerField(min_value=1)

    def clean_quantity(self):
        quantity = self.cleaned_data['quantity']
        if int(quantity) <= 0:
            raise ValidationError('تعداد باید بیشتر از 1 باشد')
        return quantity


class CouponCodeForm(forms.Form):
    code = forms.CharField(max_length=100, required=True)


class OrderCheckoutForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('recipient_name', 'recipient_phone_number', 'recipient_address')

    def clean_recipient_name(self):
        recipient_name = self.cleaned_data['recipient_name']
        if len(recipient_name) < 5:
            raise ValidationError('نام گیرنده را کامل وارد کنید')
        return recipient_name

    def clean_recipient_phone_number(self):
        recipient_phone_number = self.cleaned_data['recipient_phone_number']
        if len(recipient_phone_number) != 11:
            raise ValidationError('شماره تلفن وارد شده معتبر نمی‌باشد')
        return recipient_phone_number

    def clean_recipient_address(self):
        recipient_address = self.cleaned_data['recipient_address']
        if len(recipient_address) < 10:
            raise ValidationError('آدرس گیرنده را کامل وارد کنید')
        return recipient_address

orders/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from .cart import Cart
from products.models import Product
from .forms import CartAddFormForm, CouponCodeForm, OrderCheckoutForm
from .models import Order, OrderItem, Payment, Coupon
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from .utils import get_cart_infos
from . import pay
from django.http import HttpResponse


class CartView(View):
    def get(self, request):
        cart = Cart(request)
        form = CouponCodeForm()
        coupon_code, coupon_discount, total_price, discount_price, total_cost = get_cart_infos(request)
        return render(request, 'orders/cart.html', {
            'cart': cart, 'form': form,
            'coupon_code': coupon_code,
            'coupon_discount': coupon_discount,
            'total_price': f'{total_price:,}',
            'discount_price': f'{discount_price:,}',
            'total_cost': f'{total_cost:,}',
        })


class CartAddView(View):
    def post(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        form = CartAddFormForm(request.POST)
        if form.is_valid():
            cart.add(product, form.cleaned_data['quantity'])
        return redirect('orders:cart')


class CartRemoveView(View):
    def get(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        cart.remove(product)
        return redirect('orders:cart')


class CartUpdateView(View):
    def post(self, request):
        cart = Cart(request)
        cart.update(request.POST.get('quantity'))
        return redirect('orders:cart')


class CouponCodeView(View):
    def post(self, request):
        form = CouponCodeForm(request.POST)
        if form.is_valid():
            code = form.cleaned_data['code']
            now = timezone.now()
            try:
                coupon = Coupon.objects.get(code__exact=code, valid_to__gte=now, active=True)
                request.session['coupon_code'] = coupon.code
                request.session['coupon_discount'] = coupon.discount
            except Coupon.DoesNotExist:
                messages.error(request, 'کد تخفیف وارد شده معتبر نمی‌باشد', 'danger')
            return redirect('orders:cart')
        return redirect('orders:cart')


class CouponCodeDeleteView(View):
    def get(self, request):
        del request.session['coupon_code']
        del request.session['coupon_discount']
        return redirect('orders:cart')


class CheckoutView(LoginRequiredMixin, View):
    form_class = OrderCheckoutForm

    def get(self, request):
        cart = Cart(request)
        if not cart:
            return redirect('orders:cart')

        form = self.form_class
        coupon_code, coupon_discount, total_price, discount_price, total_cost = get_cart_infos(request)

        quantity_messages = cart.check_quantiry()

        if len(quantity_messages) == 0:
            return render(request, 'orders/checkout.html', {
                'cart': cart, 'form': form,
                'coupon_code': coupon_code,
                'coupon_discount': coupon_discount,
                'total_price': f'{total_price:,}',
                'discount_price': f'{discount_price:,}',
                'total_cost': f'{total_cost:,}',
            })
        else:
            for msg in quantity_messages:
                messages.error(request, msg, 'danger')
            form = CouponCodeForm(request.POST)
            return render(request, 'orders/cart.html', {
                'cart': cart, 'form': form,
                'coupon_code': coupon_code,
                'coupon_discount': coupon_discount,
                'total_price': f'{total_price:,}',
                'discount_price': f'{discount_price:,}',
                'total_cost': f'{total_cost:,}',
            })

    def post(self, request):
        cart = Cart(request)
        if not cart:
            return redirect('orders:cart')

        form = self.form_class(request.POST)
        coupon_code, coupon_discount, total_price, discount_price, total_cost = get_cart_infos(request)

        if form.is_valid():
            cd = form.cleaned_data
            order = Order.objects.create(
                user=request.user,
                recipient_name=cd['recipient_name'],
                recipient_phone_number=cd['recipient_phone_number'],
                recipient_address=cd['recipient_address'],
                coupon_code=coupon_code,
                coupon_discount=coupon_discount
            )
            for item in cart:
                OrderItem.objects.create(
                    order=order,
                    product=item['product'],
                    price=item['price'].replace(',', ''),
                    quantity=item['quantity']
                )
            return pay.send(request, order)

        return render(request, 'orders/checkout.html', {
            'cart': cart, 'form': form,
            'coupon_code': coupon_code,
            'coupon_discount': coupon_discount,
            'total_price': f'{total_price:,}',
            'discount_price': f'{discount_price:,}',
            'total_cost': f'{total_cost:,}',
        })


class OrderPayVerify(View):
    def get(self, request):
        return pay.verify(request)

templates/orders/cart.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block page_title %}سبد خرید{% endblock %}
{% block site_title %}سبد خرید{% endblock %}

{% block extra_js %}
<script>
    change_quantity();
    function change_quantity(){
        var products_quantity = ''
        var inputs=document.getElementsByClassName('quantity-input');
        for (let index = 0; index < inputs.length; index++) {
            products_quantity = products_quantity + inputs[index].value + ',';
        }
        document.getElementById('products_quantity').value = products_quantity;
        console.log(products_quantity)
    }

    {% if coupon_code %}
        document.getElementById('coupon_code').value = '{{coupon_code}}';
    {% endif %}

</script>
{% endblock %}

{% block page_content %}
{% if cart %}
<section class="cart-area ptb-100">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12">
                <div class="cart-table table-responsive">
                    {% include 'inc/messages.html' %}
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th scope="col">ردیف</th>
                                <th scope="col">تصویر محصول</th>
                                <th scope="col">نام محصول</th>
                                <th scope="col">قیمت واحد</th>
                                <th scope="col">تعداد</th>
                                <th scope="col">قیمت کل</th>
                                <th scope="col">پاک کردن</th>
                            </tr>
                        </thead>

                        <tbody>
                            {% for item in cart %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td class="product-thumbnail">
                                    <a href="{% url 'products:products_detail' item.product.slug %}">
                                        <img src="{{ item.product.image.url }}" alt="item">
                                    </a>
                                </td>

                                <td class="product-name">
                                    <a href="{% url 'products:products_detail' item.product.slug %}">{{ item.product.name }}</a>
                                </td>

                                <td class="product-price">
                                    <span class="unit-amount">{{item.price}} تومان</span>
                                </td>

                                <td class="product-quantity">
                                    {% comment %} {{item.quantity}} {% endcomment %}
                                    <input type="number" onchange="change_quantity()" class="form-control quantity-input" min="1" max={{item.product.stock_quantity}} value="{{item.quantity}}">
                                </td>

                                <td class="product-subtotal">
                                    <span class="subtotal-amount">{{item.total_price}} تومان</span>
                                </td>

                                <td class="product-remove">
                                    <a href="{% url 'orders:cart_remove' item.product.id %}"><i class="icofont-ui-delete"></i></a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

                <div class="cart-buttons">
                    <div class="row h-100 justify-content-center align-items-center">
                        <div class="col-lg-7 col-md-7">
                            <div class="coupon-box">
                                <form action="{% url 'orders:cart_coupon' %}" method="post" style="display:inline-flex;">
                                    {% csrf_token %}
                                    {{ form.code|add_class:"form-control text-center"|attr:"id:coupon_code"|attr:"placeholder:کد تخفیف"}}
                                    <input class="btn btn-primary" type="submit" value="اعمال کردن کد تخفیف" style="margin-right:10px;">
                                </form>
                            </div>
                        </div>

                        <div class="col-lg-5 col-md-5 text-right">
                            <form action="{% url 'orders:cart_update' %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="quantity" id="products_quantity" value="">
                                <input class="btn btn-primary" type="submit" value="به روز رسانی سبد خرید">
                            </form>
                        </div>
                    </div>
                </div>

                <div class="cart-totals">
                    <div class="row">
                        <div class="col-lg-12 col-md-12">
                            <h3>مجموع سبد</h3>

                            <ul>
                                <li>جمع کل : <span>{{total_price}} تومان</span></li>
                                <li>
                                    {% if coupon_code and coupon_discount %}
                                        مقدار تخفیف : ({{coupon_discount}} درصد تخفیف با کد {{coupon_code}})
                                        <a href="{% url 'orders:cart_coupon_delete' %}" class="delete-coupon-code">حذف کد</a> 
                                    {% else %}
                                    مقدار تخفیف : 
                                    {% endif %}
                                    <span>{{discount_price}} تومان</span>
                                </li>
                                <li>مبلغ قابل پرداخت: <span>{{total_cost}} تومان</span></li>
                            </ul>
                            <a href="{% url 'orders:checkout' %}" class="btn btn-primary">تایید و ادامه</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% else %}
<br><br>
<h1 class="text-center">
    سبد خرید شما خالی است
</h1>
{% endif %}
{% endblock %}

templates/orders/checkout.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block page_title %}بررسی سفارش{% endblock %}
{% block site_title %}بررسی سفارش{% endblock %}

{% block page_content %}
<section class="checkout-area ptb-100">
    <div class="container">
        <form action="" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-lg-6 col-md-12">
                    <div class="billing-details">
                        <h3 class="title">جزئیات صورتحساب</h3>
                        <div class="bar"></div>
                        <div class="row">
                            <div class="col-lg-12 col-md-12">
                                <div class="form-group">
                                    <label>نام گیرنده <span class="required">*</span></label>
                                    {% if form.recipient_name.errors %}
                                        {{ form.recipient_name|add_class:"form-control text-center is-invalid"}}
                                        <small class="invalid-feedback">{{ form.recipient_name.errors }}</small>
                                    {% else %}
                                        {{ form.recipient_name|add_class:"form-control text-center"}}
                                    {% endif %}
                                </div>
                            </div>
                            <div class="col-lg-12 col-md-12">
                                <div class="form-group">
                                    <label>شماره تلفن<span class="required">*</span></label>
                                    {% if form.recipient_phone_number.errors %}
                                        {{ form.recipient_phone_number|add_class:"form-control text-center is-invalid"}}
                                        <small class="invalid-feedback">{{ form.recipient_phone_number.errors }}</small>
                                    {% else %}
                                        {{ form.recipient_phone_number|add_class:"form-control text-center"}}
                                    {% endif %}
                                </div>
                            </div>
                            <div class="col-lg-12 col-md-12">
                                <div class="form-group">
                                    <label>آدرس کامل<span class="required">*</span></label>
                                    {% if form.recipient_address.errors %}
                                        {{ form.recipient_address|add_class:"form-control text-center is-invalid"}}
                                        <small class="invalid-feedback">{{ form.recipient_address.errors }}</small>
                                    {% else %}
                                        {{ form.recipient_address|add_class:"form-control text-center"}}
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-6 col-md-12">
                    <div class="order-details">
                        <h3 class="title">سفارش شما</h3>
                        <div class="bar"></div>

                        <div class="order-table table-responsive">
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th scope="col">نام محصول</th>
                                        <th scope="col">تعداد</th>
                                        <th scope="col">قیمت</th>
                                    </tr>
                                </thead>

                                <tbody>
                                    {% for item in cart %}
                                    <tr>
                                        <td class="product-name">
                                            {{item.product.name}}
                                        </td>
                                        <td class="product-name text-center">
                                            {{item.quantity}}
                                        </td>
                                        <td class="product-total text-center">
                                            {{item.total_price}} تومان
                                        </td>
                                    </tr>
                                    {% endfor %}

                                    <tr>
                                        <td class="total-price">
                                            <span>مبلغ کل سفارش</span>
                                        </td>
                                        <td></td>
                                        <td class="product-subtotal text-center">
                                            <span class="subtotal-amount">{{total_price}} تومان</span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="total-price">
                                            <span>مقدار تخفیف</span>
                                        </td>
                                        <td></td>
                                        <td class="product-subtotal text-center">
                                            <span class="subtotal-amount">{{discount_price}} تومان</span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="total-price">
                                            <span>مبلغ قابل پرداخت</span>
                                        </td>
                                        <td></td>
                                        <td class="product-subtotal text-center">
                                            <span class="total-cost-price">{{total_cost}} تومان</span>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <input type="submit" value="پرداخت و ثبت سفارش" class="btn btn-primary order-btn">
                    </div>
                </div>

            </div>
        </form>
    </div>
</section>
{% endblock %}