config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', HomeView.as_view(), name='home'),
    path('', include('products.urls', namespace='products')),
    path('', include('orders.urls', namespace='orders')),
    path('panel/', include('panel.urls', namespace='panel')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
    path('cart/update/', views.CartUpdateView.as_view(), name='cart_update'),
    path('cart/coupon/', views.CouponCodeView.as_view(), name='cart_coupon'),
    path('cart/coupon/delete/', views.CouponCodeDeleteView.as_view(), name='cart_coupon_delete'),
    path('cart/checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('orders/pay/verify/', views.OrderPayVerify.as_view(), name='pay_verify'),
]

panel/urls.py
from django.urls import path
from . import views


app_name = 'panel'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('orders/', views.OrderListView.as_view(), name='order_list'),
    path('orders/<int:pk>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('payments/', views.PaymentListView.as_view(), name='payments'),
]

products/urls.py
from django.urls import path
from . import views


app_name = 'products'

urlpatterns = [
    path('products/', views.ProductList.as_view(), name='products_list'),
    path('products/<slug:slug>/', views.ProductDetail.as_view(), name='products_detail'),
    path('category/<slug:slug>/', views.CategoryProductList.as_view(), name='category_products'),
]

templates/inc/footer.html
{% load static %}

<footer class="footer-area ptb-100 pb-0 bg-image">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6">
                <div class="single-footer-widget">
                    <a href="#" class="logo"><img src="{% static 'crake/assets/img/logo2.png' %}" alt="logo2"></a>
                    <p>برنامه روزانه، هفته یا ماه را پیش ببرید و وضعیت پروژه را در یک نگاه ببینید. جستجو و فیلتر برای تمرکز بر روی هر چیزی یک پروژه واحد فردی.</p>

                    <ul class="social-list">
                        <li><a href="#"><i class="icofont-facebook"></i></a></li>
                        <li><a href="#"><i class="icofont-twitter"></i></a></li>
                        <li><a href="#"><i class="icofont-instagram"></i></a></li>
                        <li><a href="#"><i class="icofont-linkedin"></i></a></li>
                    </ul>
                </div>
            </div>

            <div class="col-lg-3 col-md-6">
                <div class="single-footer-widget pl-5">
                    <h3>شرکت</h3>

                    <ul class="list">
                        <li><a href="#">درباره</a></li>
                        <li><a href="#">شغل ها</a></li>
                        <li><a href="#">جوایز</a></li>
                        <li><a href="#">برنامه کاربر</a></li>
                        <li><a href="#">مکان ها</a></li>
                        <li><a href="#">ورود</a></li>
                    </ul>
                </div>
            </div>

            <div class="col-lg-3 col-md-6">
                <div class="single-footer-widget">
                    <h3>محصولات</h3>

                    <ul class="list">
                        <li><a href="#">یکپارچگی</a></li>
                        <li><a href="#">شناسه</a></li>
                        <li><a href="#">قیمت</a></li>
                        <li><a href="#">مستندات</a></li>
                        <li><a href="#">ثبت نام</a></li>
                        <li><a href="#">یادداشتها</a></li>
                    </ul>
                </div>
            </div>

            <div class="col-lg-3 col-md-6">
                <div class="single-footer-widget">
                    <h3>پشتیبانی</h3>

                    <ul class="list">
                        <li><a href="#">درباره</a></li>
                        <li><a href="#">تماس</a></li>
                        <li><a href="#">گفت و گو</a></li>
                        <li><a href="#">مطبوعات</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="copyright-area">
        <div class="container">
            <div class="row h-100 justify-content-center align-items-center">
                <div class="col-lg-6 col-md-6">
                    <p>کپی رایت @  1400 | کراک | طراح و توسعه سایت جعفر عباسی.</p>
                </div>
                
                <div class="col-lg-6 col-md-6">
                    <ul>
                        <li><a href="#">شرایط و ضوابط</a></li>
                        <li><a href="#">سیاست حفظ حریم خصوصی</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/inc/header.html
{% load static %}
{% load custom_tags %}

<!-- Start Navbar Area -->
<header id="header">
    <div class="crake-mobile-nav">
        <div class="logo">
            <img src="{% static 'crake/assets/img/logo.png' %}" alt="">
        </div>
    </div>
    
    <div class="crake-nav">
        <div class="container">
            <nav class="navbar navbar-expand-md navbar-light">
                <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'crake/assets/img/logo.png' %}" alt="logo"></a>
                <div class="collapse navbar-collapse mean-menu" id="navbarSupportedContent">
                    <ul class="navbar-nav nav">
                        <li class="nav-item"><a href="{% url 'home' %}" class="nav-link">خانه</a></li>
                        <li class="nav-item"><a href="{% url 'products:products_list' %}" class="nav-link">محصولات</a></li>
                        {% navbar_category %}                   
                    </ul>
                </div>
                <div class="mr-auto others-option">
                    <ul class="navbar-nav">
                        <li class="nav-item cart-wrapper">
                            <a href="{% url 'panel:home' %}">
                                <i class="icofont-user"></i>
                            </a>
                        </li>
                        &nbsp;
                        &nbsp;
                        <li class="nav-item cart-wrapper">
                            <a href="{% url 'orders:cart' %}">
                                <i class="icofont-shopping-cart cart-icon"></i>
                                <span>{{ cart|length }}</span>
                            </a>
                        </li>
                        <li class="header-search-box">
                            <a href="#header-search" title="Search">
                                <i class="icofont-search-2"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div> 
    </div>
</header>
<!-- End Navbar Area -->

<!-- Start Search Box -->
<div id="header-search" class="header-search">
    <button type="button" class="close">×</button>
    <form action="{% url 'products:products_list' %}" method="get" class="header-search-form">
        <input type="search" name="q" placeholder="همینجا تایپ کنید........" />
        <button type="submit" class="btn btn-primary">جستجو</button>
    </form>
</div>
<!-- End Search Box -->

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <div class="alert alert-{{ msg.tags }} alert-dismissible fade show" role="alert">
            {{ msg }}
            <a href="#" type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </a>
        </div>
    {% endfor %}
{% endif %}

{% for error in form.non_field_errors %}
    {{error}}
{% endfor %}